apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # Labels for the Deployment object itself
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  replicas: 1
  selector:
    # The Deployment uses these to find and manage its Pods
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  # Template defines the Pods that will be created
  template:
    metadata:
      # These MUST match the 'selector' labels above
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
      - name: shipping
        image: prasanthreddymps/shipping:1.0.0
        imagePullPolicy: Always # safe to pull everytime
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20

