apiVersion: v1
kind: Service # to know other nodes ip in cluster for data replication
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  clusterIP: None
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306 # servie port
    targetPort: 3306 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels: 
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  serviceName: "mysql-headless" # we should attach headless service
  #replicas: 3
  replicas: 1 # by default is 1
  # Pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: prasanthreddymps/mysql:1.0.0
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # PVC
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service # for load balancing
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306 # servie port
    targetPort: 3306 # container port